export enum ExceptionCode {
    ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID',
    ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED',
    NOT_FOUND = 'GENERIC.NOT_FOUND',
    CONFLICT = 'GENERIC.CONFLICT',
    INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR',
}
